- hosts: all
  tasks:
    - name: Set all_hosts_ips
      set_fact:
        all_hosts_ips: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | map('to_json') | join(', ') }}"
 
    - debug:
        msg="{{all_hosts_ips}}"
